name: Build and deploy ASP.Net Core app to Azure Web App - ClientPortalApiDemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: |
          cd Backend
          dotnet restore Order_System.sln

      - name: Build with dotnet
        run: |
          cd Backend
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd Backend
          dotnet publish -c Release -o ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp  # Ensure to download the artifact to the correct path

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ClientPortalApiDemo'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FAB112D375A4BC6920F42E783AA0950 }}
